//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Convenience_Store_Entyti
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public string aUsername { get; set; }
        public string aPassword { get; set; }
        public string eID { get; set; }
        public string aEmail { get; set; }
        public Nullable<bool> Active { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
